name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.9.2+1
homepage: https://github.com/cachapa/firedart

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  http: ^1.0.0
  grpc:
    git:
      url: https://github.com/BST-Forked-Projects/grpc-dart.git
  protobuf: ^2.1.0
  fixnum: ^1.1.0

dev_dependencies:
  lints: any
  test: any
